var todayDate=new Date();
console.log('todays date',todayDate);
console.log( 'Day',todayDate.getDay());
console.log('Year',todayDate.getFullYear());
console.log('Month',todayDate.getMonth());
console.log('Date',todayDate.getDate()); 
var constMilli = new Date(0);
console.log('date',constMilli);
var constString = new Date('nov 10');
console.log('Date String Constructor ',constString);
var constYear = new Date(2017,10);
console.log('Date Year Constructor ',constYear);